version: 2
jobs:
  build:
    docker:
      - image: chriz2600/quartus-lite
    steps:
      - checkout

      - run:
          name: build
          command: /opt/intelFPGA_lite/18.1/quartus/bin//quartus_sh --flow compile NES
