---

name: CI
on: [push, pull_request]

jobs:
  build: 
    name: build job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: print info
      run: |
        pwd
        ls -l
    - uses: docker://chriz2600/quartus-lite
      with:
        args: /usr/local/bin/quartus_wrapper quartus_sh --flow compile NES
